services:
  - type: web
    name: fright-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fright_tool_db
          property: connectionString
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: REMEMBER_COOKIE_SECURE
        value: true
      - key: REMEMBER_COOKIE_HTTPONLY
        value: true

databases:
  - name: fright_tool_db
    databaseName: fright_tool
    user: fright_tool 