"""Remove email verification fields

Revision ID: b803dd0d2578
Revises: 
Create Date: 2025-04-01 09:03:42.076964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b803dd0d2578'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('reset_token_expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True))

    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
